server:
  port: 80
  servlet:
    context-path: /if

spring:
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl